// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:yarn/adapters/adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(MyPatternAdapter());
    registerAdapter(NeedleAdapter());
    registerAdapter(ProjectAdapter());
    registerAdapter(YarnAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(MyPatternAdapter());
    registerAdapter(NeedleAdapter());
    registerAdapter(ProjectAdapter());
    registerAdapter(YarnAdapter());
  }
}
